// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://fojtlzgvbhasumaadzhk.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvanRsemd2Ymhhc3VtYWFkemhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE4NDU3MjYsImV4cCI6MjA0NzQyMTcyNn0.-bBjw_9p_Fod0KzsoegCub9tVJTlPzfPctxyNwaWILU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);